export const SQUARES_AMOUNT_HORIZONTAL = 5;
export const SQUARES_AMOUNT_VERTICAL = 5;

export const SQUARE_CONTAINER_SIZE = 35;
export const PADDING = 1;
export const SQUARE_SIZE = SQUARE_CONTAINER_SIZE - PADDING;

export const CANVAS_WIDTH =
  SQUARES_AMOUNT_HORIZONTAL * SQUARE_CONTAINER_SIZE + PADDING + 32;
export const CANVAS_HEIGHT =
  SQUARES_AMOUNT_VERTICAL * SQUARE_CONTAINER_SIZE + PADDING + 32;
